project_name: zzz

builds:
  - main: ./main.go
    ldflags:
      - -s -w -X 'github.com/sohaha/zzz/util.BuildTime={{.Date}}' -X 'github.com/sohaha/zzz/util.Version={{.Version}} -X github.com/sohaha/zzz/util.BuildGoVersion={{.Env.GOVERSION}}'
    goos:
      - windows
      - linux
      - darwin
    # goarch:
    goarm:
      - 6
      - 7
    ignore:
    env:
      - CGO_ENABLED=0
      - GOVERSION_NR=$(go version | awk '{print $3;}')
      - GO111MODULE=on

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: 'next'

changelog:
  # skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - (?i)--
